### PR TITLE
Added My Sprites

### PR DESCRIPTION
**Pull request by hammouda101010**
it would be cool if i could see this "Coffee Engine" thing!

### CODE REVIEW

**Review by hammouda101010 — COMMENTED** [review]
fine

**Comment by David-Orangemoon** [comment]
When I get back from work I'll take a proper look at it.

**Comment by hammouda101010** [comment]
will i test Coffe Engine? (note: i don't use discord)

**Comment by AlexSchoolOH** [comment]
> will i test Coffe Engine?

I'll invite ya to the beta. Once I get a stable version of the GUI working I'll send out the private beta.

**Pull request merged**
